### ISSUE TITLE
Installation fails: sqlite3.OperationalError: no such table: user

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/pgadmin_ynh#4]
Hi,

I get an error while trying to install this app:

```
2020-03-31 13:46:51,113: DEBUG - + declare -Ar args_array
2020-03-31 13:46:51,115: DEBUG - + local user
2020-03-31 13:46:51,116: DEBUG - + local password
2020-03-31 13:46:51,117: DEBUG - + local database
2020-03-31 13:46:51,118: DEBUG - + ynh_handle_getopts_args --user=postgres --password=********** --database=
2020-03-31 13:46:51,119: DEBUG - + set +x
2020-03-31 13:46:51,120: DEBUG - + database=
2020-03-31 13:46:51,121: DEBUG - + sudo --login --user=postgres PGUSER=postgres PGPASSWORD=********** psql ''
2020-03-31 13:46:51,924: DEBUG - CREATE ROLE
2020-03-31 13:46:52,026: DEBUG - + ynh_replace_string --match_string __PYTHON_VERSION__ --replace_string 3.5 --target_file config_database.py
2020-03-31 13:46:52,027: DEBUG - + local legacy_args=mrf
2020-03-31 13:46:52,028: DEBUG - + args_array=([m]=match_string= [r]=replace_string= [f]=target_file=)
2020-03-31 13:46:52,030: DEBUG - + declare -Ar args_array
2020-03-31 13:46:52,031: DEBUG - + local match_string
2020-03-31 13:46:52,032: DEBUG - + local replace_string
2020-03-31 13:46:52,033: DEBUG - + local target_file
2020-03-31 13:46:52,035: DEBUG - + ynh_handle_getopts_args --match_string __PYTHON_VERSION__ --replace_string 3.5 --target_file config_database.py
2020-03-31 13:46:52,036: DEBUG - + set +x
2020-03-31 13:46:52,037: DEBUG - + local delimit=@
2020-03-31 13:46:52,038: DEBUG - + match_string=__PYTHON_VERSION__
2020-03-31 13:46:52,040: DEBUG - + replace_string=3.5
2020-03-31 13:46:52,041: DEBUG - + sudo sed --in-place s@__PYTHON_VERSION__@3.5@g config_database.py
2020-03-31 13:46:52,144: DEBUG - + /opt/yunohost/pgadmin/bin/python3 config_database.py pgadmin **********
2020-03-31 13:46:52,446: DEBUG - + ynh_exit_properly
2020-03-31 13:46:52,447: WARNING - Traceback (most recent call last):
2020-03-31 13:46:52,449: DEBUG - + local exit_code=1
2020-03-31 13:46:52,451: WARNING -   File "config_database.py", line 18, in <module>
2020-03-31 13:46:52,453: DEBUG - + '[' 1 -eq 0 ']'
2020-03-31 13:46:52,454: WARNING -     cursor = conn.execute('SELECT `password`,1 FROM `user`')
2020-03-31 13:46:52,456: DEBUG - + trap '' EXIT
2020-03-31 13:46:52,457: WARNING - sqlite3.OperationalError: no such table: user
2020-03-31 13:46:52,459: DEBUG - + set +eu
2020-03-31 13:46:52,460: DEBUG - + sleep 0.5
2020-03-31 13:46:52,963: DEBUG - + type -t ynh_clean_setup
2020-03-31 13:46:52,964: WARNING - 
2020-03-31 13:46:52,967: DEBUG - + ynh_die
2020-03-31 13:46:52,969: DEBUG - + local legacy_args=mc
2020-03-31 13:46:52,970: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2020-03-31 13:46:52,972: DEBUG - + declare -Ar args_array
2020-03-31 13:46:52,973: DEBUG - + local message
2020-03-31 13:46:52,974: DEBUG - + local ret_code
2020-03-31 13:46:52,975: DEBUG - + ynh_handle_getopts_args
2020-03-31 13:46:52,976: DEBUG - + set +x
2020-03-31 13:46:52,976: DEBUG - + echo ''
2020-03-31 13:46:52,977: DEBUG - + exit 1
2020-03-31 13:46:53,100: ERROR - Impossible d'installer pgadmin: Une erreur est survenue dans le script d'installation de l'application
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 301, in wrapper
    curr_v = params[k]
KeyError: 'label'
```

This seems to come from https://github.com/YunoHost-Apps/pgadmin_ynh/blob/testing/scripts/config_database.py#L18 but I don't know why it tries to use sqlite? By the way there is a small typo line 17 ("encrypte" misses a final "d").

Can you help debug please?

**Comment by Josue-T** [comment]
> I don't know why it tries to use sqlite?

Because the pgadmin user data is stored in sqlite

Can you try maybe a second time and give me the full log of the install ?

**Comment by nicofrand** [comment]
Oh, how ironic.

Second install, same error: https://nicofrand.eu/yunohost/admin/#/tools/logs/20200331-151605-app_install-pgadmin?number=500

**Comment by Josue-T** [comment]
Thanks but your link is broken...

**Comment by nicofrand** [comment]
I just edited the link, sorry about that

**Comment by Josue-T** [comment]
For me this issue is probably here 
```
2020-03-31 17:23:23,167: DEBUG - + sudo sed --in-place s@__ADMIN_PASSWORD__@**********@g ../conf/setup.exp
2020-03-31 17:23:23,168: DEBUG - + ../conf/setup.exp /opt/yunohost/pgadmin/bin/python3 /opt/yunohost/pgadmin/lib/python3.5/site-packages/pgadmin4/setup.py mail@nicofrand.eu
2020-03-31 17:23:23,369: DEBUG - spawn /opt/yunohost/pgadmin/bin/python3 /opt/yunohost/pgadmin/lib/python3.5/site-packages/pgadmin4/setup.py
2020-03-31 17:23:28,887: DEBUG - NOTE: Configuring authentication for SERVER mode.
2020-03-31 17:23:28,890: DEBUG - 
2020-03-31 17:23:28,891: DEBUG - Enter the email address and password to use for the initial pgAdmin user account:
2020-03-31 17:23:28,892: DEBUG - 
2020-03-31 17:23:28,893: DEBUG - Email address: mail@nicofrand.eu
2020-03-31 17:23:28,894: DEBUG - Password:
2020-03-31 17:23:28,895: DEBUG - Retype password:+ ynh_script_progression '--message=Configuring Postgresql database...'
```
Normally the database should be initialised and probably the database was not initialized.

Did you use a password with some special char ? If yes it could be an reason to fail.

You can mybe try to install with the arg `-n` which avoid to remove the app when the install fail. After you can try to investigate way it fail.

**Comment by nicofrand** [comment]
No, no specials chars (and different at each try).

**Comment by nicofrand** [comment]
OK weird, I tried in CLI with `-n` but this time the installation worked…

**Comment by jedie** [comment]
I get the same error: https://paste.yunohost.org/raw/riwoqazofe

**Comment by jorgesat** [comment]
I have the same error.

Please find the log [here](https://paste.yunohost.org/raw/ofekuluvim).

**Comment by farvardin** [comment]
> I have the same error.
> 
> Please find the log [here](https://paste.yunohost.org/raw/ofekuluvim).
> 
> **Solved** after installing it from terminal.

same for me. Webinstall is broken, but I could install it from terminal as well.

**Comment by zyphlar** [comment]
Same, also worked via CLI

```
2021-06-03 21:18:24,455: DEBUG - + systemctl is-active postgresql@11-main -q
2021-06-03 21:18:24,460: DEBUG - + systemctl is-enabled postgresql -q
2021-06-03 21:18:24,467: DEBUG - + '[' '!' -f /etc/yunohost/psql ']'
2021-06-03 21:18:24,468: DEBUG - + ynh_psql_execute_as_root --sql 'CREATE USER pgadmin WITH PASSWORD '\''**********'\'' SUPERUSER CREATEDB CREATEROLE REPLICATION'
2021-06-03 21:18:24,511: DEBUG - + database=
2021-06-03 21:18:24,511: DEBUG - + '[' -n '' ']'
2021-06-03 21:18:24,512: DEBUG - ++ cat /etc/yunohost/psql
2021-06-03 21:18:24,514: DEBUG - + ynh_psql_connect_as --user=postgres --password=**********
2021-06-03 21:18:24,572: DEBUG - + database=
2021-06-03 21:18:24,572: DEBUG - + sudo --login --user=postgres PGUSER=postgres PGPASSWORD=********** psql ''
2021-06-03 21:18:24,734: DEBUG - CREATE ROLE
2021-06-03 21:18:24,739: DEBUG - + ynh_replace_string --match_string __PYTHON_VERSION__ --replace_string 3.7 --target_file config_database.py
2021-06-03 21:18:24,913: DEBUG - + local delimit=@
2021-06-03 21:18:24,913: DEBUG - + match_string=__PYTHON_VERSION__
2021-06-03 21:18:24,913: DEBUG - + replace_string=3.7
2021-06-03 21:18:24,913: DEBUG - + sed --in-place s@__PYTHON_VERSION__@3.7@g config_database.py
2021-06-03 21:18:24,916: DEBUG - + /opt/yunohost/pgadmin/bin/python3 config_database.py pgadmin **********
2021-06-03 21:18:24,977: WARNING - config_database.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
2021-06-03 21:18:24,978: WARNING -   import imp
2021-06-03 21:18:24,978: WARNING - Traceback (most recent call last):
2021-06-03 21:18:24,979: WARNING -   File "config_database.py", line 18, in <module>
2021-06-03 21:18:24,979: WARNING -     cursor = conn.execute('SELECT `password`,1 FROM `user`')
2021-06-03 21:18:24,979: WARNING - sqlite3.OperationalError: no such table: user
2021-06-03 21:18:24,985: DEBUG - + ynh_exit_properly
2021-06-03 21:18:24,985: DEBUG - + local exit_code=1
2021-06-03 21:18:24,985: DEBUG - + rm -rf /var/cache/yunohost/download/
2021-06-03 21:18:24,988: DEBUG - + '[' 1 -eq 0 ']'
2021-06-03 21:18:24,988: DEBUG - + trap '' EXIT
2021-06-03 21:18:24,988: DEBUG - + set +o errexit
2021-06-03 21:18:24,988: DEBUG - + set +o nounset
2021-06-03 21:18:24,988: DEBUG - + sleep 0.5
2021-06-03 21:18:25,491: DEBUG - + type -t ynh_clean_setup
2021-06-03 21:18:25,491: DEBUG - + exit 1
2021-06-03 21:18:26,494: ERROR - Unable to install pgadmin: An error occurred inside the app installation script
```

**Comment by navanchauhan** [comment]
Same error: https://paste.yunohost.org/raw/vikeqemoji

**Comment by tutle** [comment]
Finally succeed to install trough command line in putty and login with email address (not the user name).

**Comment by rubensflinco** [comment]
Same error for me I'm installing through the web follows my log:  https://paste.yunohost.org/raw/ipojomohen

**Comment by OlivierMary** [comment]
Hi here,
Same: https://paste.yunohost.org/raw/focapipitu

I try @tutle tutorial.

**Comment by OlivierMary** [comment]
Success with `sudo yunohost app install https://github.com/YunoHost-Apps/pgadmin_ynh/tree/testing --debug`

And with user email without ext `.local`

**Comment by Salamandar** [comment]
Should be fixed now.
